name: Create github issue for each post
on:
  push:
    branches:
      - master
jobs:
  create-github-issue-for-each-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create github issue for each post
        run: .github/workflows/create-github-issue-for-each-post.sh
