name: Create github issue for each post
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create github issue for each post
        run: |
          echo -e "\\033[1;36mgrep permalink _posts/* | cut -d' ' -f2 | tr '/' '-'\\033[0;02m"
          grep permalink _posts/* | cut -d' ' -f2 | tr '/' '-'
